apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  clusterIP: None                  # Create a headless service
  selector:
    app: redis                     # Match the Pods with this label
  ports:
    - port: 6379                   # Port exposed by the Service
      targetPort: 6379             # Port the Pods are listening on
