apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: payment-service
spec:
  host: payment-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL        # Use mTLS for outbound traffic
  subsets:
    - name: v1
      labels:
        version: v1             # Label selector for version v1
    - name: v2
      labels:
        version: v2             # Label selector for version v2
