---
- name: install and start the web servers
  hosts: all
  remote_user: deploy_user
  become: true
  vars:
    port: 80
    server_name: example.com
    document_root: /var/www/html
  tasks:

    - name: install nginx
      apt:
        name: nginx
        state: present
      notify: restart-nginx

    - name: Deploy nginx configuration file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart-nginx

    - name: copy the file to remote with back up
      copy:
        src: /home/my-folder/my-file.txt
        dest: /home/dev/files/
        backup: yes
        owner: data-user
        group: data-user
        mode: '0644'

  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted
